### PR TITLE
TF-11948 : Add Index Execution_ID in Activiti table

### PR DESCRIPTION
**Pull request by psaputra**
Relates : [TF-11948](https://jira.office.dgitsystems.com/browse/TF-11948)

### CODE REVIEW

**Comment by svasani** [comment]
Update Activiti version to '5.21.0.dgit-fix-9' is required.

commit showing how to do it https://github.com/dgit-hub/Activiti/pull/4/commits/bf9daf3e130b325ab03e40bd3d43fbf53a982d47

**Comment by svasani** [comment]
Script that updates database from 5.20 to 5.21 needs to be updated to include this index. Otherwise any customer still using pre Telflow 9.4 wont get this change.

**Comment by psaputra** [comment]
> Update Activiti version to '5.21.0.dgit-fix-9' is required.
> 
> commit showing how to do it [bf9daf3](https://github.com/dgit-hub/Activiti/commit/bf9daf3e130b325ab03e40bd3d43fbf53a982d47)

done

**Comment by psaputra** [comment]
> Script that updates database from 5.20 to 5.21 needs to be updated to include this index. Otherwise any customer still using pre Telflow 9.4 wont get this change.

done

**Review by svasani — APPROVED** [review]

**Review by mhanrahan — APPROVED** [review]

**Pull request merged**
